remote_theme: mmistakes/minimal-mistakes
title: Dental Group AI4H ITU/WIPO/WHO Global Initiative Review Results
description: Editable version of the results of the ITU/WHO Global Initiative Dental Group's review of public datasets for dental imaging AI.
